/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api720d8ea9",
            "endpoint": "https://whb5pd8nq9.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://u4fmdwnorrf73ouwbgtm4vjl64.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oqcjhs6tyzbynegtebydzlauym",
    "aws_cognito_identity_pool_id": "us-west-1:9fe2b296-cc3f-467b-8c21-4e824c923cbb",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_SvhvGsKlG",
    "aws_user_pools_web_client_id": "77nu0vi3bh9vosim31u4rfdiv7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
